---
title: "**Tips and tricks**"
output:
  html_document:
    toc: false
    toc_float: false
from: markdown+emoji
---

## nf-core/rnaseq 

* [nf-core/rnaseq user guide](https://nf-co.re/rnaseq/3.12.0)
* [nf-core tools utility](https://nf-co.re/tools)
* [nf-core download instructions](https://nf-co.re/tools#downloading-pipelines-for-offline-use)
* [nf-core institutional configs](https://nf-co.re/configs)
* [nf-core Slack channel](https://nf-co.re/join/slack/)

## R container and notebook  

This workshop is designed to be portable and reproducible. We have provided the Rmd file and RStudio/4.0.1 container for you to use:

* [RNA differential expression notebook](https://github.com/Sydney-Informatics-Hub/rna-differential-expression-Rnotebook)
* [RStudio/4.0.1 for RNAseq container](https://github.com/Sydney-Informatics-Hub/Rstudio-rnaseq-contained)

## Additional training 

* [nf-core training calendar](https://nf-co.re/events/training)
* [nf-core tutorials](https://nf-co.re/docs/usage/tutorials)
* [Customising nf-core workshop](https://sydney-informatics-hub.github.io/customising-nfcore-workshop/)
* [Intro to the shell exercises](https://linuxjourney.com/lesson/the-shell)
* [R for reproducible science workshop](https://swcarpentry.github.io/r-novice-gapminder/index.html)

## Troubleshooting 

### Error when trying to run rserver on Nimbus

When you run the command
```default
mkdir -p /tmp/rstudio-server  

PASSWORD='abc' singularity exec \  
    -B /tmp/rstudio-server:/var/lib/rstudio-server \  
    -B /tmp/rstudio-server:/var/run/rstudio-server \  
    -B /home/ubuntu/working_directory/Day-2:/home \   
    rstudio_4.1.0.sif \  
    rserver --auth-none=0 --auth-pam-helper-path=pam-helper --server-user ubuntu  

```
If an error similar to the one below pops up - 

::: {.callout-note appearance="simple"}
11 Oct 2023 23:14:42 [rserver] ERROR system error 98 (Address already in use); OCCURRED AT   rstudio::core::Error rstudio::core::http::initTcpIpAcceptor (rstudio::core::http::SocketAcceptorService<rstudio_boost::asio::ip::tcp>&, const string&, const string&) src/cpp/server/ServerInit.cpp:103; LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:704
:::

Do the following
```default
rm -r  /tmp/rstudio-server
sudo lsof -i :8787
```

If you see:
```default
COMMAND PID           USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
rserver 747 rstudio-server    7u  IPv4  19251      0t0  TCP *:8787 (LISTEN)
```

Run the command: 
```default
sudo kill <PID> 
```
Here substitute <PID> with the corresponding PID value e.g. 747 above

### RStudio not loading in browser

If you need to end your session, exit your browser and on Nimbus, run the following command:

```default
kill -9 $(lsof -t -c rsession)
```

### Loop device error on Nimbus

When running Singularity containers on Nimbus you may come across an error:
```default
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs 
error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: no loop devices available
```
Run the following commands to resolve this issue: 
```default
lsmod | grep loop
```
```default
sudo modprobe loop
```
```default
sudo losetup -f
```
```default
/dev/loop9
```